documentation:
  - any: ['README.md', 'docs/**/*']

dependencies:
  - any: ['package.json', 'package-lock.json']

source:
  - any: ['src/**/*']
  - all: ['!src/__tests__/**/*', '!src/**/*.test.ts']

tests:
  - any: ['src/__tests__/**/*', 'src/**/*.test.ts']

examples:
  - any: ['src/examples/**/*']